### ISSUE TITLE
getAll() and get() with options to return full relationships and relationship shortcut entities

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-model#1]
For loading all resources of certain kind to GUI etc. with just one query, we may need getAll() and get() methods of model library to return requested resources with full entities, e.g., field 'materials' contains an entity Material with all its properties set, not only 'href' and 'class'.

**Comment by mhelvens** [comment]
No longer relevant in view of the removal of 1st class relationships.
