### ISSUE TITLE
Add deleteAll method for a given class

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-model#2]
REST API allows users to delete all relationships of a certain class, for efficient implementation of this operation we need a library method ClassName.deleteAll() which is than fulfilled by one query in an external method implemented by the server instead of numerous delete methods of a specific relationship.

**Comment by mhelvens** [comment]
It can be done, but why do we need this operation? It's not standard REST, and supporting it may be ill-advised from a safety point of view. There's a reason I didn't add it to the initial REST API.

**Comment by albatros13** [comment]
My fault in description, REST API indeed does not expose delete method for all relationships, I implemented this operation on server for testing, it was only called directly from tests in fact. Ok, it is optional then, we can close the issue.
