### ISSUE TITLE
Switch identifiers from href to id

### ISSUE THREAD

**Issue by mhelvens** [open-physiology/open-physiology-model#6]
Several reasons:
* Requests for multiple resources at the same time
* Easier to form relationship put/delete requests

**Comment by mhelvens** [comment]
Issue moved to [open-physiology/open-physiology #16](https://github.com/open-physiology/open-physiology/issues/16) via [**ZenHub**](https://www.zenhub.com/)

**Comment by albatros13** [comment]
Updated model library fails complaining about images (see issue on image storage), the problem needs to be solved before we can review this issue.

**Comment by albatros13** [comment]
How to distinguish resources with ID placeholders from resources with actual IDs? 
Before I was generating permanent hrefs when ID was empty, now this method does not work anymore.

**Comment by mhelvens** [comment]
`.isPlaceholder` should work. Otherwise, you can test whether `typeof id
=== 'undefined'`.

-- 
www.mhelvens.net
